CREATE TABLE `order_address` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `address_id` int(10) unsigned NOT NULL COMMENT '地址ID',
  `order_id` int(10) unsigned NOT NULL COMMENT '订单ID',
  `shop_id` int(10) unsigned NOT NULL COMMENT '门店ID',
  `user_id` int(10) unsigned NOT NULL COMMENT '用户ID',
  `name` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '名称',
  `phone` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '手机号',
  `sex` enum('male','female') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'male' COMMENT '性别',
  `address` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '地址',
  `description` varchar(50) COLLATE utf8mb4_unicode_ci NULL COMMENT '描述',
  `longitude` varchar(30) COLLATE utf8mb4_unicode_ci NULL COMMENT '经度',
  `latitude` varchar(30) COLLATE utf8mb4_unicode_ci NULL COMMENT '纬度',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` timestamp NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `order_addresses_address_id_index` (`address_id`),
  KEY `order_addresses_order_id_index` (`order_id`),
  KEY `order_addresses_user_id_index` (`user_id`),
  KEY `order_addresses_name_index` (`name`),
  KEY `order_addresses_phone_index` (`phone`),
  KEY `order_addresses_sex_index` (`sex`),
  KEY `order_addresses_shop_id_index` (`shop_id`),
  KEY `idx_order_ads_01` (`created_at`),
  KEY `idx_order_ads_02` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单地址';