CREATE TABLE `order_items` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `order_id` int(10) unsigned NOT NULL COMMENT '订单ID',
  `shop_id` int(10) unsigned NOT NULL COMMENT '门店ID',
  `product_id` int(10) unsigned NOT NULL COMMENT '商品ID',
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '名称',
  `sku_id` int(10) unsigned NULL COMMENT 'SKU ID',
  `quantity` int(10) unsigned NOT NULL COMMENT '数量',
  `discount_price` decimal(6,2) NOT NULL DEFAULT '0.00' COMMENT '优惠价格',
  `box_fee` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '打包费',
  `price` decimal(8,2) NOT NULL COMMENT '商品价格',
  `total_fee` decimal(8,2) NOT NULL COMMENT '总金额',
  `actual_quantity` varchar(10) COLLATE utf8mb4_unicode_ci NULL COMMENT '实际数量',
  `actual_total_fee` decimal(8,2) NULL COMMENT '总金额',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` timestamp NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `order_items_order_id_index` (`order_id`),
  KEY `order_items_product_id_index` (`product_id`),
  KEY `order_items_quantity_index` (`quantity`),
  KEY `order_items_name_index` (`name`),
  KEY `order_items_shop_id_index` (`shop_id`),
  KEY `order_items_discount_price_index` (`discount_price`),
  KEY `order_items_created_at_IDX` (`created_at`) USING BTREE,
  KEY `idx_order_items_01` (`updated_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单详情项';