CREATE TABLE `orders` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `no` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '订单号',
  `user_id` int(10) unsigned NOT NULL COMMENT '用户ID',
  `phone` varchar(191) COLLATE utf8mb4_unicode_ci  NULL COMMENT '手机号',
  `shop_id` int(10) unsigned NOT NULL COMMENT '门店ID',
  `is_takeaway` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否外卖',
  `location` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '用户下单经纬度',
  `total_fee` decimal(8,2) NOT NULL COMMENT '总金额',
  `payment` decimal(8,2) NOT NULL COMMENT '实付金额',
  `box_fee` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '打包费',
  `delivery_fee` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '配送费',
  `discount_fee` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '优惠金额',
  `coupon_fee` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '微信代金券或立减优惠金额',
  `status` enum('WAIT_BUYER_PAY','BUYER_PAY','WAIT_SELLER_SEND_GOODS','WAIT_BUYER_CONFIRM_GOODS','DISPATCHING_GOODS','TRADE_CLOSED','CANCELED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'WAIT_BUYER_PAY' COMMENT '状态',
  `remarks` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '订单备注',
  `pickup_time` datetime DEFAULT NULL COMMENT '预约送货时间',
  `closed_at` datetime DEFAULT NULL COMMENT '关闭时间',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` timestamp NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `orders_no_index` (`no`),
  KEY `orders_user_id_index` (`user_id`),
  KEY `orders_phone_index` (`phone`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单表'